[build]
  base = "/"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_USE_YARN = "false"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ces redirections sont importantes pour les applications Next.js
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
